version: '3.4'

services:
  ossqa-database:
    image: ossqa-database
    build:
      context: .
      dockerfile: src/database/Dockerfile
    env_file: .env
    ports:
      - "5080:5080"
    expose:
      - "5080"

  ossqa-base:
    image: ossqa
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - ossqa-database
    network_mode: host
    env_file: .env
    expose:
      - "5080"
      - "8080"

  ossqa-prototype:
    image: ossqa-prototype
    build:
      context: .
      dockerfile: ./src/prototype/Dockerfile
    env_file: .env
    
  ossqa-tests:
    image: ossqa-tests
    build:
      context: .
      dockerfile: ./src/tests/Dockerfile
    env_file: .env

  ossqa:
    image: ossqa
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - ossqa-database
    network_mode: host
    env_file: .env
    expose:
      - "5080"
    command: ["python", "__main__.py", "&"]

  ossqa-frontend:
    image: ${DOCKER_REGISTRY-}ossqa-frontend
    build:
      context: .
      dockerfile: ./src/OSSQAWebAPI/Dockerfile
    ports:
     - "8080:8080"
    depends_on:
        - ossqa-database  





