version: '3.4'

services:
  ossqa:
    image: ossqa
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env

  ossqa-prototype:
    image: ossqa-prototype
    build:
      context: .
      dockerfile: ./src/prototype/Dockerfile
    env_file: .env
    
  ossqa-tests:
    image: ossqa-tests
    build:
      context: .
      dockerfile: ./src/tests/Dockerfile
    env_file: .env

