name: Docker Image CI

on:
  push:
  # Branch 18 used for testing
  # TODO: Delete when testing is complete. It should not be here.
    branches: [ "main", "18-research-and-apply-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Echo secrets
      run: |
        echo $TEST_ENV_FILE >> ./.env
        cat ./.env
      shell: bash
      env:
        # Feel free to rename this variable, but make sure to update it everywhere. You should paste your entire file in your secrets
        TEST_ENV_FILE : GITHUB_AUTH_TOKEN=${{secrets.AUTH_TOKEN}}
    - name: Build the Docker image
      run: docker compose build ossqa-prototype 
    - name: Run tests
      run: docker compose run ossqa-prototype
#    - name: Run python tests.
#      run: docker-compose py-test
