name: Docker Image CI Test

on:
  push:
    branches: [ "dev", "dev-unstable"]
  pull_request:
    branches: [ "main", "dev", "dev-unstable"]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create env file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false
    - name: Read env file
      uses: falti/dotenv-action@v1.1.2
    - name: Build the Docker image
      run: docker compose build ossqa-tests
    - name: Run tests
      run: docker compose run --name ossqa-tests-container ossqa-tests
    - name: Print test logs
      run: |
        docker cp ossqa-tests-container:/app/test_logs.txt ./test_logs.txt
        echo "$(cat ./test_logs.txt)"
    - name: Print function coverage
      run: |
        docker cp ossqa-tests-container:/app/.coverage.function ./.coverage.function
        echo "$(cat ./.coverage.function)"
