name: Docker Image CI

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "main", "dev"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Echo secrets
      run: |
        echo $ENV_FILE >> ./.env
        cat ./.env
      shell: bash
      env:
        ENV_FILE : ${{secrets.AUTH_TOKEN}}

    - name: Build the Docker image
      run: docker compose build ossqa-prototype 
    - name: Run tests
      run: docker compose run ossqa-prototype
#    - name: Run python tests.
#      run: docker-compose py-test
